version: "3.9"
services:
    web:
        build:
            context: .
            dockerfile: dockerfile
        env_file: 
            - .env.prod
        ports:
            - 80:8000
    #   volumes:
    #     - static_volume:/home/app/web/microservice/static      
    #   expose:
    #     - 8000
