version: '3'

tasks:
  test:
    cmds:
      - go test ./... -coverprofile=cover.out {{.CLI_ARGS}}
    vars:
      PWD:
        sh: echo '$(pwd)'

  test:cover:
    cmds:
      - go tool cover -html=cover.out

  test:cover:total:
    cmds:
      - task: test
      - go tool cover -func cover.out

  build:
    cmds:
      - templ generate
      - go run . --act=build

  web:
    cmds:
      - templ generate
      - go run . --act=web

  dev:templ:
    cmds:
      - templ generate -watch --cmd="go run . --act=web"

  dev:watch:
    cmds:
      # pip install watchdog[watchmedo]
      - > 
        ~/venv/bin/watchmedo auto-restart 
        --patterns "*.templ;*.go;*.css" 
        -i "*_templ.go"
        --recursive
        -- sh -c "task web; sleep infinity"