version: '3'

tasks:
  test:
    cmds:
      - go test ./... {{.CLI_ARGS}}
    vars:
      PWD:
        sh: echo '$(pwd)'

  build:
    cmds:
      - templ generate
      - go run . --act=build

  dev:templ:
    cmds:
      - templ generate -watch --cmd="go run . --act=web"
