- hosts: all
  become: yes
  vars:
    rep: fldarknet
  tasks:

    - name: ps
      ansible.builtin.command: docker ps -a -q --filter="name={{rep}}"
      register: example_output
      ignore_errors: yes

    - name: stop
      ansible.builtin.command: docker stop {{example_output["stdout"]}}
      ignore_errors: yes

    - name: load
      ansible.builtin.command: docker load -i fldarknet.dock

    - name: run
      ansible.builtin.command: docker run --name fldarknet -t -d -p 80:8000 --rm fldarknet:latest

    - name: prune
      ansible.builtin.command: docker image prune -a -f

    - name: docker ps
      ansible.builtin.shell: docker ps
      register: example_output

    - debug: msg="{{ example_output.stdout }}"