name: Django CI

on: [push, pull_request]

jobs:
  main-workflow:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        python scripts.py test pylint
    - name: Analysing the code with flake8
      run: |
        python scripts.py test flake
    - name: Running Unit Tests
      run: |
        python scripts.py test unit
    - name: Coverage Report
      run: |
        python scripts.py test cover
    - name: Sphinx build
      run: |
        python scripts.py sphinx build
