name: Publish to pages

on:
  workflow_call:
    inputs:
      freelancer-folder:
          description: Path to root of freelancer directory
          default: ${{ github.workspace }}
          type: string
      site-root:
          description: Site root prefix to static assets
          type: string
          default: "/"
      heading:
          description: Heading at the site rigit.
          type: string
          default: "fl-darkstat powered by <a href=\"https://github.com/darklab8/fl-darkstat\">Github</a>" 

jobs:
  github-pages:
    name: Github Pages
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
        - name: Check out source repository
          uses: actions/checkout@v2

        - name: Install Darkstat
          run: |
            curl -L $(curl -Ls -o /dev/null -w %{url_effective} https://github.com/darklab8/fl-darkstat/releases/latest | sed "s/releases\/tag/releases\/download/")/darkstat-linux-amd64 -o /usr/local/bin/darkstat && chmod 777 /usr/local/bin/darkstat

        - name: build
          run: darkstat --act=build
          env:
            SITE_ROOT: ${{ inputs.site-root }}
            FLDARKSTAT_FREELANCER_FOLDER: ${{ inputs.freelancer-folder }}
            FLDARKSTAT_HEADING: ${{ inputs.heading }}

        - uses: actions/upload-pages-artifact@v1
          with:
            name: github-pages
            path: ./build
        
        # in Repo settings / Pages / choose Build and Deployment from Github Actions
        - name: Deploy to pages
          uses: actions/deploy-pages@v1
          id: deployment
