name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pylint-django
        cd FLDarknet
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        cd FLDarknet
        pylint --load-plugins pylint_django --django-settings-module="fldarknet.settings" --disable=django-not-configured --exit-zero `ls -d */`
